## [E] POLS, FE, RE

In [1]:
import pandas as pd
import numpy as np
import os
import re

import statsmodels.api as sm
import scipy.stats as stats
from scipy.stats import chi2

from linearmodels.panel import PanelOLS, RandomEffects, PooledOLS

In [2]:
path = "data/processed_data/"
file_name = "03_pols_fe_re_gmm_winsorized_data.csv"

date_column = "date" 
stock_column = "stock"

# Set path
os.chdir("..")
print(os.getcwd())

/workspaces/master-thesis-submission/src

In [3]:
pols_fe_re_data = pd.read_csv(path + file_name)

In [4]:
pols_fe_re_data.head()

,date,stock,stock_return_quarterly,beta,size,value,profitability,investment,price_momentum,esg_score,esg_momentum,industry,country_of_headquarters
0,2016-06-30,A2.MI,0.030621,1.470557,22.009083,0.748281,0.079054,-0.033443,-0.036842,59.459100,-1.622974,Utilities,Italy
1,2016-06-30,AAL.L,0.250263,0.558792,23.225868,1.461129,-0.304424,0.000000,0.324333,81.434442,-7.452243,Basic Materials,United Kingdom
2,2016-06-30,AALB.AS,-0.112824,1.229154,21.818938,0.424145,0.194845,0.000000,0.014720,17.964003,5.607441,Industrials,Netherlands
3,2016-06-30,ABBN.S,0.029602,0.988284,24.365696,0.362603,0.200431,0.011075,0.041707,88.899243,-3.994408,Industrials,Switzerland
4,2016-06-30,ABDN.L,-0.217060,1.664075,22.662034,0.796699,0.150175,0.000000,-0.256856,74.424211,-0.391662,Financials,United Kingdom

## Analysis

In [5]:
def omitted_base_category(series):
    cats = sorted(series.dropna().astype(str).unique())
    return cats[0] if len(cats) else None, cats

In [6]:
def run_pols(df, include_time_dummies_pols_re=False):

    df = df.copy()
    df[date_column] = pd.to_datetime(df[date_column], errors="coerce")

    # Set multi-index for panel data
    df = df.set_index([stock_column, date_column]).sort_index()

    # Define dependent and independent variables
    reg_vars = [
        "beta", 
        "size", 
        "value", 
        "profitability", 
        "investment",
        "price_momentum", 
        "esg_score", 
        "esg_momentum"
    ]

    base = df[reg_vars].copy()

    base_industry, industries = omitted_base_category(df["industry"])
    base_country, countries = omitted_base_category(df["country_of_headquarters"])

    print("Omitted base industry:", base_industry)
    print("Omitted base country:", base_country)

    industry_dummy = pd.get_dummies(df["industry"], drop_first=True, dtype=float)
    country_dummy = pd.get_dummies(df["country_of_headquarters"], drop_first=True, dtype=float)

    # Dependent variable
    y = df["stock_return_quarterly"]

    # Base X used for FE models (unchanged)
    X_base = pd.concat([base, industry_dummy, country_dummy], axis=1)
    X_base = sm.add_constant(X_base).astype(float)

    # Optional time dummies only for POLS and RE
    if include_time_dummies_pols_re:
        time_values = pd.Series(
            df.index.get_level_values(date_column),
            index=df.index,
            name="time_period"
        )
        
        time_dummy = pd.get_dummies(time_values, prefix="time", drop_first=True, dtype=float)

        X_pols_re = pd.concat([X_base, time_dummy], axis=1)
        X_pols_re = X_pols_re.astype(float)
    else:
        X_pols_re = X_base.copy()

    # Pooled OLS
    pooled_ols_model = PooledOLS(y, X_pols_re)
    pooled_ols_results = pooled_ols_model.fit(cov_type="clustered", cluster_entity=True)

    # Two-way Fixed Effects Model
    fe_model_two_way = PanelOLS(y, X_base, entity_effects=True, time_effects=True, drop_absorbed=True)
    fe_results_two_way = fe_model_two_way.fit(cov_type="clustered", cluster_entity=True)

    # Random Effects Model
    re_model = RandomEffects(y, X_pols_re)
    re_results = re_model.fit(cov_type="clustered", cluster_entity=True)
    re_theta = re_results.theta

    return pooled_ols_results, fe_results_two_way, re_results, re_theta

### Panel Regressions

In [7]:
pooled_ols_result, fe_results, re_result, re_theta = run_pols(pols_fe_re_data, include_time_dummies_pols_re=True)

Omitted base industry: Basic Materials
Omitted base country: Austria

/tmp/ipykernel_14438/2178028754.py:60: AbsorbingEffectWarning:
Variables have been fully absorbed and have removed from the regression:

Consumer Discretionary, Consumer Staples, Energy, Financials, Health Care, Industrials, Real Estate, Technology, Telecommunications, Utilities, Belgium, Bermuda, Cyprus, Czech Republic, Denmark, Faroe Islands, Finland, France, Germany, Hungary, Ireland, Isle of Man, Israel, Italy, Jersey, Kazakhstan, Luxembourg, Malta, Mexico, Netherlands, Norway, Poland, Portugal, South Africa, Spain, Sweden, Switzerland, United Kingdom, United States of America

  fe_results_two_way = fe_model_two_way.fit(cov_type="clustered", cluster_entity=True)

In [ ]:
def results_to_df(results):
    """ This function exports the pols, fe, and re results to xlsx """
    ci = results.conf_int()
    ci.columns = ["ci_lower", "ci_upper"]

    out = pd.concat(
        [
            results.params.rename("coef"),
            results.std_errors.rename("std_error"),
            results.tstats.rename("t_stat"),
            results.pvalues.rename("p_value"),
            ci,
        ],
        axis=1
    )
    out.index.name = "variable"
    return out

pooled_df = results_to_df(pooled_ols_result)
fe_df = results_to_df(fe_results)
re_df = results_to_df(re_result)

with pd.ExcelWriter(path + "05_panel_model_results.xlsx", engine="openpyxl") as writer:
    pooled_df.to_excel(writer, sheet_name="POLS")
    fe_df.to_excel(writer, sheet_name="FE")
    re_df.to_excel(writer, sheet_name="RE")

print("Results Exported to 05_panel_model_results.xlsx")

Results Exported to 05_panel_model_results.xlsx

In [10]:
pooled_ols_result

                            PooledOLS Estimation Summary
====================================================================================
Dep. Variable:     stock_return_quarterly   R-squared:                        0.4418
Estimator:                      PooledOLS   R-squared (Between):              0.6510
No. Observations:                   20184   R-squared (Within):               0.4323
Date:                    Fri, May 08 2026   R-squared (Overall):              0.4418
Time:                            09:20:11   Log-likelihood                 1.481e+04
Cov. Estimator:                 Clustered
                                            F-statistic:                      189.40
Entities:                             804   P-value                           0.0000
Avg Obs:                           25.104   Distribution:                F(84,20099)
Min Obs:                           1.0000
Max Obs:                           38.000   F-statistic (robust):          2.584e+16
                                            P-value                           0.0000
Time periods:                          38   Distribution:                F(84,20099)
Avg Obs:                           531.16
Min Obs:                           468.00
Max Obs:                           548.00

                                    Parameter Estimates
============================================================================================
                          Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------
const                       -0.1702     0.0153    -11.121     0.0000     -0.2003     -0.1402
beta                         0.0031     0.0011     2.8519     0.0044      0.0010      0.0053
size                         0.0075     0.0006     11.966     0.0000      0.0063      0.0087
value                       -0.0155     0.0023    -6.6406     0.0000     -0.0201     -0.0110
profitability               -0.0094     0.0028    -3.4088     0.0007     -0.0149     -0.0040
investment                   0.0101     0.0090     1.1227     0.2616     -0.0075      0.0278
price_momentum               0.3343     0.0054     61.490     0.0000      0.3236      0.3449
esg_score                -6.049e-05  4.064e-05    -1.4884     0.1366     -0.0001   1.917e-05
esg_momentum              6.382e-05     0.0001     0.5345     0.5930     -0.0002      0.0003
Consumer Discretionary      -0.0051     0.0023    -2.2189     0.0265     -0.0096     -0.0006
Consumer Staples            -0.0103     0.0026    -3.9641     0.0001     -0.0154     -0.0052
Energy                      -0.0021     0.0034    -0.6157     0.5381     -0.0089      0.0046
Financials                   0.0037     0.0024     1.5224     0.1279     -0.0011      0.0084
Health Care                 -0.0087     0.0025    -3.5077     0.0005     -0.0136     -0.0038
Industrials                  0.0008     0.0022     0.3587     0.7198     -0.0035      0.0050
Real Estate                  0.0040     0.0027     1.4810     0.1386     -0.0013      0.0092
Technology                  -0.0066     0.0031    -2.1108     0.0348     -0.0127     -0.0005
Telecommunications          -0.0063     0.0028    -2.2081     0.0273     -0.0119     -0.0007
Utilities                   -0.0036     0.0024    -1.4804     0.1388     -0.0083      0.0012
Belgium                     -0.0067     0.0051    -1.3156     0.1883     -0.0168      0.0033
Bermuda                     -0.0085     0.0040    -2.1460     0.0319     -0.0162     -0.0007
Cyprus                       0.0307     0.0038     8.0228     0.0000      0.0232      0.0382
Czech Republic               0.0003     0.0041     0.0612     0.9512     -0.0078      0.0083
Denmark                     -0.0067     0.0042    -1.6213     0.1050     -0.0149      0.0014
Faroe Islands                0.0027     0.0039     0.6788     0.4972     -0.0050      0.0103
Finland                     -0.0060     0.0040    -1.4825     0.1382     -0.0139      0.0019
France                      -0.0079     0.0037    -2.1305     0.0331     -0.0152     -0.0006
Germany                     -0.0078     0.0039    -1.9944     0.0461     -0.0154     -0.0001
Hungary                     -0.0919     0.0049    -18.639     0.0000     -0.1016     -0.0823
Ireland                     -0.0076     0.0042    -1.8322     0.0669     -0.0158      0.0005
Isle of Man                 -0.0270     0.0040    -6.7639     0.0000     -0.0348     -0.0192
Israel                      -0.0161     0.0047    -3.4099     0.0007     -0.0254     -0.0069
Italy                       -0.0036     0.0041    -0.8948     0.3709     -0.0116      0.0043
Jersey                      -0.0075     0.0055    -1.3513     0.1766     -0.0184      0.0034
Kazakhstan                  -0.0075     0.0042    -1.7712     0.0765     -0.0159      0.0008
Luxembourg                  -0.0014     0.0051    -0.2627     0.7928     -0.0114      0.0087
Malta                        0.0012     0.0040     0.3004     0.7639     -0.0067      0.0091
Mexico                       0.0199     0.0045     4.4460     0.0000      0.0111      0.0286
Netherlands                 -0.0029     0.0042    -0.6942     0.4876     -0.0113      0.0054
Norway                      -0.0054     0.0048    -1.1223     0.2617     -0.0148      0.0040
Poland                       0.0038     0.0076     0.4976     0.6187     -0.0111      0.0187
Portugal                    -0.0042     0.0038    -1.1021     0.2705     -0.0116      0.0033
South Africa                -0.0600     0.0499    -1.2031     0.2289     -0.1579      0.0378
Spain                       -0.0065     0.0041    -1.5839     0.1132     -0.0147      0.0016
Sweden                      -0.0077     0.0038    -2.0080     0.0447     -0.0151     -0.0002
Switzerland                 -0.0107     0.0039    -2.7512     0.0059     -0.0183     -0.0031
United Kingdom              -0.0068     0.0036    -1.8816     0.0599     -0.0139      0.0003
United States of America    -0.0043     0.0038    -1.1435     0.2528     -0.0118      0.0031
time_2016-09-30 00:00:00     0.0653     0.0083     7.8711     0.0000      0.0491      0.0816
time_2016-12-31 00:00:00     0.0612     0.0079     7.7557     0.0000      0.0457      0.0767
time_2017-03-31 00:00:00     0.0555     0.0067     8.3287     0.0000      0.0424      0.0686
time_2017-06-30 00:00:00    -0.0318     0.0064    -5.0104     0.0000     -0.0443     -0.0194
time_2017-09-30 00:00:00     0.0357     0.0066     5.4280     0.0000      0.0228      0.0486
time_2017-12-31 00:00:00     0.0293     0.0067     4.4041     0.0000      0.0163      0.0424
time_2018-03-31 00:00:00    -0.0287     0.0064    -4.5029     0.0000     -0.0411     -0.0162
time_2018-06-30 00:00:00     0.0493     0.0076     6.4961     0.0000      0.0344      0.0641
time_2018-09-30 00:00:00     0.0128     0.0069     1.8553     0.0636     -0.0007      0.0262
time_2018-12-31 00:00:00    -0.0848     0.0066    -12.791     0.0000     -0.0977     -0.0718
time_2019-03-31 00:00:00     0.1660     0.0071     23.302     0.0000      0.1521      0.1800
time_2019-06-30 00:00:00     0.0181     0.0065     2.7818     0.0054      0.0054      0.0309
time_2019-09-30 00:00:00     0.0356     0.0070     5.0805     0.0000      0.0219      0.0493
time_2019-12-31 00:00:00     0.0553     0.0075     7.4109     0.0000      0.0407      0.0700
time_2020-03-31 00:00:00    -0.2361     0.0079    -29.819     0.0000     -0.2517     -0.2206
time_2020-06-30 00:00:00     0.2208     0.0089     24.699     0.0000      0.2032      0.2383
time_2020-09-30 00:00:00     0.0507     0.0077     6.5659     0.0000      0.0355      0.0658
time_2020-12-31 00:00:00     0.1074     0.0098     10.982     0.0000      0.0882      0.1266
time_2021-03-31 00:00:00     0.0394     0.0073     5.3901     0.0000      0.0251      0.0538
time_2021-06-30 00:00:00     0.0130     0.0065     1.9904     0.0466      0.0002      0.0258
time_2021-09-30 00:00:00    -0.0377     0.0069    -5.4543     0.0000     -0.0512     -0.0242
time_2021-12-31 00:00:00     0.0636     0.0067     9.4762     0.0000      0.0504      0.0768
time_2022-03-31 00:00:00    -0.0414     0.0077    -5.3762     0.0000     -0.0565     -0.0263
time_2022-06-30 00:00:00    -0.0966     0.0069    -13.905     0.0000     -0.1102     -0.0829
time_2022-09-30 00:00:00    -0.0198     0.0070    -2.8131     0.0049     -0.0336     -0.0060
time_2022-12-31 00:00:00     0.1423     0.0080     17.761     0.0000      0.1266      0.1580
time_2023-03-31 00:00:00     0.0680     0.0078     8.7030     0.0000      0.0527      0.0833
time_2023-06-30 00:00:00    -0.0025     0.0064    -0.3903     0.6963     -0.0151      0.0101
time_2023-09-30 00:00:00    -0.0027     0.0072    -0.3696     0.7117     -0.0167      0.0114
time_2023-12-31 00:00:00     0.1041     0.0078     13.391     0.0000      0.0889      0.1194
time_2024-03-31 00:00:00     0.0347     0.0075     4.6417     0.0000      0.0201      0.0494
time_2024-06-30 00:00:00    -0.0353     0.0067    -5.2773     0.0000     -0.0485     -0.0222
time_2024-09-30 00:00:00     0.0485     0.0074     6.5814     0.0000      0.0341      0.0630
time_2024-12-31 00:00:00    -0.0203     0.0070    -2.8992     0.0037     -0.0340     -0.0066
time_2025-03-31 00:00:00     0.0331     0.0081     4.0977     0.0000      0.0172      0.0489
time_2025-06-30 00:00:00     0.0402     0.0077     5.2336     0.0000      0.0252      0.0553
time_2025-09-30 00:00:00     0.0201     0.0067     2.9936     0.0028      0.0069      0.0333
============================================================================================
PanelResults, id: 0x7fb4889542d0

In [11]:
fe_results

                            PanelOLS Estimation Summary
====================================================================================
Dep. Variable:     stock_return_quarterly   R-squared:                        0.2253
Estimator:                       PanelOLS   R-squared (Between):              0.3246
No. Observations:                   20184   R-squared (Within):               0.2007
Date:                    Fri, May 08 2026   R-squared (Overall):              0.1657
Time:                            09:20:11   Log-likelihood                 1.512e+04
Cov. Estimator:                 Clustered
                                            F-statistic:                      702.97
Entities:                             804   P-value                           0.0000
Avg Obs:                           25.104   Distribution:                 F(8,19335)
Min Obs:                           1.0000
Max Obs:                           38.000   F-statistic (robust):             734.89
                                            P-value                           0.0000
Time periods:                          38   Distribution:                 F(8,19335)
Avg Obs:                           531.16
Min Obs:                           468.00
Max Obs:                           548.00

                               Parameter Estimates
==================================================================================
                Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
----------------------------------------------------------------------------------
const             -0.7595     0.1000    -7.5982     0.0000     -0.9554     -0.5636
beta               0.0034     0.0013     2.6232     0.0087      0.0009      0.0060
size               0.0358     0.0044     8.1893     0.0000      0.0272      0.0443
value             -0.0421     0.0074    -5.6886     0.0000     -0.0566     -0.0276
profitability     -0.0106     0.0049    -2.1495     0.0316     -0.0203     -0.0009
investment         0.0082     0.0088     0.9313     0.3517     -0.0091      0.0255
price_momentum     0.3046     0.0066     46.484     0.0000      0.2918      0.3174
esg_score         -0.0005     0.0001    -3.7756     0.0002     -0.0008     -0.0003
esg_momentum       0.0002     0.0001     1.6827     0.0925   -4.11e-05      0.0005
==================================================================================

F-test for Poolability: 10.856
P-value: 0.0000
Distribution: F(840,19335)

Included effects: Entity, Time
PanelEffectsResults, id: 0x7fb487733f10

In [12]:
re_result

                          RandomEffects Estimation Summary
====================================================================================
Dep. Variable:     stock_return_quarterly   R-squared:                        0.4418
Estimator:                  RandomEffects   R-squared (Between):              0.6510
No. Observations:                   20184   R-squared (Within):               0.4323
Date:                    Fri, May 08 2026   R-squared (Overall):              0.4418
Time:                            09:20:12   Log-likelihood                 1.481e+04
Cov. Estimator:                 Clustered
                                            F-statistic:                      189.40
Entities:                             804   P-value                           0.0000
Avg Obs:                           25.104   Distribution:                F(84,20099)
Min Obs:                           1.0000
Max Obs:                           38.000   F-statistic (robust):          2.584e+16
                                            P-value                           0.0000
Time periods:                          38   Distribution:                F(84,20099)
Avg Obs:                           531.16
Min Obs:                           468.00
Max Obs:                           548.00

                                    Parameter Estimates
============================================================================================
                          Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------------
const                       -0.1702     0.0153    -11.121     0.0000     -0.2003     -0.1402
beta                         0.0031     0.0011     2.8519     0.0044      0.0010      0.0053
size                         0.0075     0.0006     11.966     0.0000      0.0063      0.0087
value                       -0.0155     0.0023    -6.6406     0.0000     -0.0201     -0.0110
profitability               -0.0094     0.0028    -3.4088     0.0007     -0.0149     -0.0040
investment                   0.0101     0.0090     1.1227     0.2616     -0.0075      0.0278
price_momentum               0.3343     0.0054     61.490     0.0000      0.3236      0.3449
esg_score                -6.049e-05  4.064e-05    -1.4884     0.1366     -0.0001   1.917e-05
esg_momentum              6.382e-05     0.0001     0.5345     0.5930     -0.0002      0.0003
Consumer Discretionary      -0.0051     0.0023    -2.2189     0.0265     -0.0096     -0.0006
Consumer Staples            -0.0103     0.0026    -3.9641     0.0001     -0.0154     -0.0052
Energy                      -0.0021     0.0034    -0.6157     0.5381     -0.0089      0.0046
Financials                   0.0037     0.0024     1.5224     0.1279     -0.0011      0.0084
Health Care                 -0.0087     0.0025    -3.5077     0.0005     -0.0136     -0.0038
Industrials                  0.0008     0.0022     0.3587     0.7198     -0.0035      0.0050
Real Estate                  0.0040     0.0027     1.4810     0.1386     -0.0013      0.0092
Technology                  -0.0066     0.0031    -2.1108     0.0348     -0.0127     -0.0005
Telecommunications          -0.0063     0.0028    -2.2081     0.0273     -0.0119     -0.0007
Utilities                   -0.0036     0.0024    -1.4804     0.1388     -0.0083      0.0012
Belgium                     -0.0067     0.0051    -1.3156     0.1883     -0.0168      0.0033
Bermuda                     -0.0085     0.0040    -2.1460     0.0319     -0.0162     -0.0007
Cyprus                       0.0307     0.0038     8.0228     0.0000      0.0232      0.0382
Czech Republic               0.0003     0.0041     0.0612     0.9512     -0.0078      0.0083
Denmark                     -0.0067     0.0042    -1.6213     0.1050     -0.0149      0.0014
Faroe Islands                0.0027     0.0039     0.6788     0.4972     -0.0050      0.0103
Finland                     -0.0060     0.0040    -1.4825     0.1382     -0.0139      0.0019
France                      -0.0079     0.0037    -2.1305     0.0331     -0.0152     -0.0006
Germany                     -0.0078     0.0039    -1.9944     0.0461     -0.0154     -0.0001
Hungary                     -0.0919     0.0049    -18.639     0.0000     -0.1016     -0.0823
Ireland                     -0.0076     0.0042    -1.8322     0.0669     -0.0158      0.0005
Isle of Man                 -0.0270     0.0040    -6.7639     0.0000     -0.0348     -0.0192
Israel                      -0.0161     0.0047    -3.4099     0.0007     -0.0254     -0.0069
Italy                       -0.0036     0.0041    -0.8948     0.3709     -0.0116      0.0043
Jersey                      -0.0075     0.0055    -1.3513     0.1766     -0.0184      0.0034
Kazakhstan                  -0.0075     0.0042    -1.7712     0.0765     -0.0159      0.0008
Luxembourg                  -0.0014     0.0051    -0.2627     0.7928     -0.0114      0.0087
Malta                        0.0012     0.0040     0.3004     0.7639     -0.0067      0.0091
Mexico                       0.0199     0.0045     4.4460     0.0000      0.0111      0.0286
Netherlands                 -0.0029     0.0042    -0.6942     0.4876     -0.0113      0.0054
Norway                      -0.0054     0.0048    -1.1223     0.2617     -0.0148      0.0040
Poland                       0.0038     0.0076     0.4976     0.6187     -0.0111      0.0187
Portugal                    -0.0042     0.0038    -1.1021     0.2705     -0.0116      0.0033
South Africa                -0.0600     0.0499    -1.2031     0.2289     -0.1579      0.0378
Spain                       -0.0065     0.0041    -1.5839     0.1132     -0.0147      0.0016
Sweden                      -0.0077     0.0038    -2.0080     0.0447     -0.0151     -0.0002
Switzerland                 -0.0107     0.0039    -2.7512     0.0059     -0.0183     -0.0031
United Kingdom              -0.0068     0.0036    -1.8816     0.0599     -0.0139      0.0003
United States of America    -0.0043     0.0038    -1.1435     0.2528     -0.0118      0.0031
time_2016-09-30 00:00:00     0.0653     0.0083     7.8711     0.0000      0.0491      0.0816
time_2016-12-31 00:00:00     0.0612     0.0079     7.7557     0.0000      0.0457      0.0767
time_2017-03-31 00:00:00     0.0555     0.0067     8.3287     0.0000      0.0424      0.0686
time_2017-06-30 00:00:00    -0.0318     0.0064    -5.0104     0.0000     -0.0443     -0.0194
time_2017-09-30 00:00:00     0.0357     0.0066     5.4280     0.0000      0.0228      0.0486
time_2017-12-31 00:00:00     0.0293     0.0067     4.4041     0.0000      0.0163      0.0424
time_2018-03-31 00:00:00    -0.0287     0.0064    -4.5029     0.0000     -0.0411     -0.0162
time_2018-06-30 00:00:00     0.0493     0.0076     6.4961     0.0000      0.0344      0.0641
time_2018-09-30 00:00:00     0.0128     0.0069     1.8553     0.0636     -0.0007      0.0262
time_2018-12-31 00:00:00    -0.0848     0.0066    -12.791     0.0000     -0.0977     -0.0718
time_2019-03-31 00:00:00     0.1660     0.0071     23.302     0.0000      0.1521      0.1800
time_2019-06-30 00:00:00     0.0181     0.0065     2.7818     0.0054      0.0054      0.0309
time_2019-09-30 00:00:00     0.0356     0.0070     5.0805     0.0000      0.0219      0.0493
time_2019-12-31 00:00:00     0.0553     0.0075     7.4109     0.0000      0.0407      0.0700
time_2020-03-31 00:00:00    -0.2361     0.0079    -29.819     0.0000     -0.2517     -0.2206
time_2020-06-30 00:00:00     0.2208     0.0089     24.699     0.0000      0.2032      0.2383
time_2020-09-30 00:00:00     0.0507     0.0077     6.5659     0.0000      0.0355      0.0658
time_2020-12-31 00:00:00     0.1074     0.0098     10.982     0.0000      0.0882      0.1266
time_2021-03-31 00:00:00     0.0394     0.0073     5.3901     0.0000      0.0251      0.0538
time_2021-06-30 00:00:00     0.0130     0.0065     1.9904     0.0466      0.0002      0.0258
time_2021-09-30 00:00:00    -0.0377     0.0069    -5.4543     0.0000     -0.0512     -0.0242
time_2021-12-31 00:00:00     0.0636     0.0067     9.4762     0.0000      0.0504      0.0768
time_2022-03-31 00:00:00    -0.0414     0.0077    -5.3762     0.0000     -0.0565     -0.0263
time_2022-06-30 00:00:00    -0.0966     0.0069    -13.905     0.0000     -0.1102     -0.0829
time_2022-09-30 00:00:00    -0.0198     0.0070    -2.8131     0.0049     -0.0336     -0.0060
time_2022-12-31 00:00:00     0.1423     0.0080     17.761     0.0000      0.1266      0.1580
time_2023-03-31 00:00:00     0.0680     0.0078     8.7030     0.0000      0.0527      0.0833
time_2023-06-30 00:00:00    -0.0025     0.0064    -0.3903     0.6963     -0.0151      0.0101
time_2023-09-30 00:00:00    -0.0027     0.0072    -0.3696     0.7117     -0.0167      0.0114
time_2023-12-31 00:00:00     0.1041     0.0078     13.391     0.0000      0.0889      0.1194
time_2024-03-31 00:00:00     0.0347     0.0075     4.6417     0.0000      0.0201      0.0494
time_2024-06-30 00:00:00    -0.0353     0.0067    -5.2773     0.0000     -0.0485     -0.0222
time_2024-09-30 00:00:00     0.0485     0.0074     6.5814     0.0000      0.0341      0.0630
time_2024-12-31 00:00:00    -0.0203     0.0070    -2.8992     0.0037     -0.0340     -0.0066
time_2025-03-31 00:00:00     0.0331     0.0081     4.0977     0.0000      0.0172      0.0489
time_2025-06-30 00:00:00     0.0402     0.0077     5.2336     0.0000      0.0252      0.0553
time_2025-09-30 00:00:00     0.0201     0.0067     2.9936     0.0028      0.0069      0.0333
============================================================================================
RandomEffectsResults, id: 0x7fb487775010

### Hausman Test

In [23]:
def hausman_fe_re(fe_res, re_res, coef_names=None):
    """
        Source: https://github.com/bilkent-sna/negotiating-comfort-with-llm-agents/blob/main/analysis.ipynb
    """

    b_fe = fe_res.params
    b_re = re_res.params

    common = b_fe.index.intersection(b_re.index)

    if coef_names is not None:
        common = pd.Index([c for c in coef_names if c in common])

    diff = (b_fe.loc[common] - b_re.loc[common]).to_numpy()

    V_fe = fe_res.cov.loc[common, common].to_numpy()
    V_re = re_res.cov.loc[common, common].to_numpy()

    V_diff = V_fe - V_re

    stat = float(diff.T @ np.linalg.pinv(V_diff) @ diff)
    df = len(common)
    pval = 1.0 - chi2.cdf(stat, df)

    return {
        "stat": stat,
        "df": df,
        "pval": pval,
        "compared_coefficients": list(common),
    }

In [24]:
hausman_fe_re(fe_results, re_result)

{'stat': 57.92930583638603,
 'df': 9,
 'pval': 3.3533722465506344e-09,
 'compared_coefficients': ['const',
  'beta',
  'size',
  'value',
  'profitability',
  'investment',
  'price_momentum',
  'esg_score',
  'esg_momentum']}

### Random Effects Deep Dive

In [ ]:
def inspect_re_variance_components(df):

    # Source: https://bashtage.github.io/linearmodels/devel/_modules/linearmodels/panel/model.html

    # Match run_pols defaults
    use_lagged_regressors = False
    include_time_dummies_pols_re = True

    df = df.copy()
    df[date_column] = pd.to_datetime(df[date_column], errors="coerce")

    # Keep only stocks with at least 2 observations
    counts = df.groupby(stock_column)[date_column].transform("count")
    df = df[counts >= 2]

    # Set panel index
    df = df.set_index([stock_column, date_column]).sort_index()

    # Same regressors as in run_pols
    reg_vars = [
        "beta", "size", "value", "profitability", "investment",
        "price_momentum", "esg_score", "esg_momentum"
    ]

    base = df[reg_vars].copy()

    if use_lagged_regressors:
        base = base.groupby(level=0).shift(1)

    industry_dummy = pd.get_dummies(df["industry"], drop_first=True, dtype=float)
    country_dummy = pd.get_dummies(df["country_of_headquarters"], drop_first=True, dtype=float)

    y = df["stock_return_quarterly"]

    X_base = pd.concat([base, industry_dummy, country_dummy], axis=1)
    X_base = sm.add_constant(X_base).astype(float)

    if include_time_dummies_pols_re:
        time_values = pd.Series(
            df.index.get_level_values(date_column),
            index=df.index,
            name="time_period"
        )
        time_dummy = pd.get_dummies(time_values, prefix="time", drop_first=True, dtype=float)
        X_pols_re = pd.concat([X_base, time_dummy], axis=1).astype(float)
    else:
        X_pols_re = X_base.copy()

    # Align and drop missing rows exactly before fitting
    valid = y.notna() & X_pols_re.notna().all(axis=1)
    y = y.loc[valid]
    X_pols_re = X_pols_re.loc[valid]

    # Fit RE model exactly as in run_pols
    re_model = RandomEffects(y, X_pols_re)
    re_results = re_model.fit(cov_type="clustered", cluster_entity=True)

    # --- Reconstruct sigma2_e and raw sigma2_u from the fitted model internals ---

    w = re_model.weights.values2d
    root_w = np.sqrt(w)

    # Weighted quasi-demeaned regression used for sigma2_e
    demeaned_dep = re_model.dependent.demean("entity", weights=re_model.weights)
    demeaned_exog = re_model.exog.demean("entity", weights=re_model.weights)

    y_within = demeaned_dep.values2d.copy()
    x_within = demeaned_exog.values2d.copy()

    if re_model.has_constant:
        w_sum = w.sum()
        y_gm = (w * re_model.dependent.values2d).sum(0) / w_sum
        x_gm = (w * re_model.exog.values2d).sum(0) / w_sum
        y_within = y_within + root_w * y_gm
        x_within = x_within + root_w * x_gm

    params_within = np.linalg.lstsq(x_within, y_within, rcond=None)[0]
    weps = y_within - x_within @ params_within

    # Between regression used for sigma2_u
    wybar = re_model.dependent.mean("entity", weights=re_model.weights)
    wxbar = re_model.exog.mean("entity", weights=re_model.weights)

    wybar_arr = np.asarray(wybar)
    wxbar_arr = np.asarray(wxbar)

    params_between = np.linalg.lstsq(wxbar_arr, wybar_arr, rcond=None)[0]
    wu = wybar_arr - wxbar_arr @ params_between

    # Dimensions used in linearmodels
    nobs = weps.shape[0]
    neffects = wu.shape[0]
    nvar = x_within.shape[1]

    sigma2_e_manual = float(np.squeeze(weps.T @ weps)) / (nobs - nvar - neffects + 1)

    t = np.asarray(re_model.dependent.count("entity"), dtype=float)
    t_bar = neffects / np.sum(1.0 / t)

    ssr_u = float(np.squeeze(wu.T @ wu))
    sigma2_u_raw = ssr_u / (neffects - nvar) - sigma2_e_manual / t_bar
    sigma2_u_after_clip = max(0.0, sigma2_u_raw)

    theta_manual = 1.0 - np.sqrt(
        sigma2_e_manual / (t * sigma2_u_after_clip + sigma2_e_manual)
    )

    theta_reported = re_results.theta["theta"].to_numpy()

    return {
        "sigma2_u_raw": sigma2_u_raw,
        "sigma2_u_after_clip": sigma2_u_after_clip,
        "sigma2_u_reported": float(re_results.variance_decomposition["Effects"]),
        "sigma2_e_manual": sigma2_e_manual,
        "sigma2_e_reported": float(re_results.variance_decomposition["Residual"]),
        "ssr_u": ssr_u,
        "t_bar": float(t_bar),
        "nobs": int(nobs),
        "neffects": int(neffects),
        "nvar": int(nvar),
        "all_theta_zero": bool((re_results.theta["theta"] == 0).all()),
        "theta_matches_manual": bool(np.allclose(theta_manual.ravel(), theta_reported)),
        "theta_summary": re_results.theta["theta"].describe(),
        "re_results": re_results,
    }

In [20]:
re_theta

              theta
stock
1COVG.DE^L25    0.0
1U1.DE          0.0
A2.MI           0.0
AAAA.L^C21      0.0
AAK.ST          0.0
...             ...
ZALG.DE         0.0
ZEG.L           0.0
ZELA.CO         0.0
ZOT.MC^E22      0.0
ZURN.S          0.0

[804 rows x 1 columns]

In [21]:
print(re_result.variance_decomposition)

Effects                   0.00000
Residual                  0.01369
Percent due to Effects    0.00000
Name: Variance Decomposition, dtype: float64

In [22]:
inspect_re_variance_components(pols_fe_re_data)

{'sigma2_u_raw': -0.0003793778224851107,
 'sigma2_u_after_clip': 0.0,
 'sigma2_u_reported': 0.0,
 'sigma2_e_manual': 0.013690035158601564,
 'sigma2_e_reported': 0.013690035158601564,
 'ssr_u': 0.46980223066521015,
 't_bar': 13.138174268419885,
 'nobs': 20174,
 'neffects': 794,
 'nvar': 85,
 'all_theta_zero': True,
 'theta_matches_manual': True,
 'theta_summary': count    794.0
 mean       0.0
 std        0.0
 min        0.0
 25%        0.0
 50%        0.0
 75%        0.0
 max        0.0
 Name: theta, dtype: float64,
 're_results':                           RandomEffects Estimation Summary
 ====================================================================================
 Dep. Variable:     stock_return_quarterly   R-squared:                        0.4414
 Estimator:                  RandomEffects   R-squared (Between):              0.6474
 No. Observations:                   20174   R-squared (Within):               0.4323
 Date:                    Fri, May 08 2026   R-squared (Overall):              0.4414
 Time:                            09:45:11   Log-likelihood                 1.481e+04
 Cov. Estimator:                 Clustered
                                             F-statistic:                      189.01
 Entities:                             794   P-value                           0.0000
 Avg Obs:                           25.408   Distribution:                F(84,20089)
 Min Obs:                           2.0000
 Max Obs:                           38.000   F-statistic (robust):         -9.023e+15
                                             P-value                           1.0000
 Time periods:                          38   Distribution:                F(84,20089)
 Avg Obs:                           530.89
 Min Obs:                           468.00
 Max Obs:                           548.00

                                     Parameter Estimates
 ============================================================================================
                           Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
 --------------------------------------------------------------------------------------------
 const                       -0.1703     0.0153    -11.113     0.0000     -0.2003     -0.1403
 beta                         0.0031     0.0011     2.8322     0.0046      0.0010      0.0053
 size                         0.0075     0.0006     11.964     0.0000      0.0063      0.0087
 value                       -0.0156     0.0023    -6.6467     0.0000     -0.0201     -0.0110
 profitability               -0.0093     0.0028    -3.3781     0.0007     -0.0148     -0.0039
 investment                   0.0093     0.0090     1.0333     0.3015     -0.0083      0.0269
 price_momentum               0.3335     0.0054     61.457     0.0000      0.3229      0.3442
 esg_score                -5.969e-05  4.036e-05    -1.4788     0.1392     -0.0001   1.942e-05
 esg_momentum              6.615e-05     0.0001     0.5538     0.5797     -0.0002      0.0003
 Consumer Discretionary      -0.0050     0.0023    -2.1857     0.0288     -0.0095     -0.0005
 Consumer Staples            -0.0103     0.0026    -3.9577     0.0001     -0.0154     -0.0052
 Energy                      -0.0023     0.0034    -0.6618     0.5081     -0.0090      0.0045
 Financials                   0.0036     0.0024     1.5067     0.1319     -0.0011      0.0084
 Health Care                 -0.0087     0.0025    -3.5148     0.0004     -0.0136     -0.0039
 Industrials                  0.0008     0.0022     0.3587     0.7198     -0.0035      0.0050
 Real Estate                  0.0040     0.0027     1.4743     0.1404     -0.0013      0.0092
 Technology                  -0.0066     0.0031    -2.1090     0.0350     -0.0127     -0.0005
 Telecommunications          -0.0067     0.0028    -2.3867     0.0170     -0.0122     -0.0012
 Utilities                   -0.0036     0.0024    -1.4933     0.1354     -0.0083      0.0011
 Belgium                     -0.0069     0.0051    -1.3436     0.1791     -0.0169      0.0032
 Bermuda                     -0.0085     0.0040    -2.1424     0.0322     -0.0162     -0.0007
 Cyprus                       0.0308     0.0038     8.0504     0.0000      0.0233      0.0384
 Czech Republic               0.0003     0.0041     0.0663     0.9472     -0.0078      0.0083
 Denmark                     -0.0068     0.0042    -1.6222     0.1048     -0.0149      0.0014
 Faroe Islands                0.0026     0.0039     0.6654     0.5058     -0.0051      0.0103
 Finland                     -0.0060     0.0040    -1.4762     0.1399     -0.0139      0.0020
 France                      -0.0080     0.0037    -2.1362     0.0327     -0.0153     -0.0007
 Germany                     -0.0078     0.0039    -1.9891     0.0467     -0.0154     -0.0001
 Hungary                     -0.0922     0.0049    -18.665     0.0000     -0.1018     -0.0825
 Ireland                     -0.0077     0.0042    -1.8423     0.0655     -0.0159      0.0005
 Isle of Man                 -0.0271     0.0040    -6.7749     0.0000     -0.0350     -0.0193
 Israel                      -0.0156     0.0047    -3.3047     0.0010     -0.0249     -0.0064
 Italy                       -0.0036     0.0041    -0.8837     0.3769     -0.0116      0.0044
 Jersey                      -0.0075     0.0055    -1.3638     0.1727     -0.0183      0.0033
 Kazakhstan                  -0.0076     0.0043    -1.7858     0.0741     -0.0159      0.0007
 Luxembourg                  -0.0013     0.0052    -0.2564     0.7977     -0.0114      0.0088
 Malta                        0.0011     0.0040     0.2693     0.7877     -0.0068      0.0090
 Mexico                       0.0201     0.0045     4.4867     0.0000      0.0113      0.0288
 Netherlands                 -0.0029     0.0043    -0.6921     0.4889     -0.0113      0.0054
 Norway                      -0.0053     0.0048    -1.1152     0.2648     -0.0148      0.0041
 Poland                       0.0038     0.0076     0.5014     0.6161     -0.0111      0.0187
 Portugal                    -0.0042     0.0038    -1.1021     0.2704     -0.0116      0.0033
 South Africa                -0.0602     0.0499    -1.2049     0.2283     -0.1580      0.0377
 Spain                       -0.0065     0.0041    -1.5750     0.1153     -0.0146      0.0016
 Sweden                      -0.0077     0.0038    -2.0162     0.0438     -0.0152     -0.0002
 Switzerland                 -0.0107     0.0039    -2.7495     0.0060     -0.0184     -0.0031
 United Kingdom              -0.0069     0.0036    -1.8876     0.0591     -0.0140      0.0003
 United States of America    -0.0044     0.0038    -1.1550     0.2481     -0.0119      0.0031
 time_2016-09-30 00:00:00     0.0654     0.0083     7.8813     0.0000      0.0491      0.0817
 time_2016-12-31 00:00:00     0.0612     0.0079     7.7595     0.0000      0.0458      0.0767
 time_2017-03-31 00:00:00     0.0557     0.0067     8.3524     0.0000      0.0426      0.0687
 time_2017-06-30 00:00:00    -0.0317     0.0064    -4.9826     0.0000     -0.0441     -0.0192
 time_2017-09-30 00:00:00     0.0358     0.0066     5.4358     0.0000      0.0229      0.0487
 time_2017-12-31 00:00:00     0.0294     0.0067     4.4103     0.0000      0.0163      0.0424
 time_2018-03-31 00:00:00    -0.0286     0.0064    -4.4869     0.0000     -0.0410     -0.0161
 time_2018-06-30 00:00:00     0.0493     0.0076     6.5028     0.0000      0.0345      0.0642
 time_2018-09-30 00:00:00     0.0129     0.0069     1.8759     0.0607     -0.0006      0.0264
 time_2018-12-31 00:00:00    -0.0848     0.0066    -12.793     0.0000     -0.0978     -0.0718
 time_2019-03-31 00:00:00     0.1661     0.0071     23.309     0.0000      0.1521      0.1800
 time_2019-06-30 00:00:00     0.0182     0.0065     2.7965     0.0052      0.0054      0.0310
 time_2019-09-30 00:00:00     0.0357     0.0070     5.0873     0.0000      0.0219      0.0494
 time_2019-12-31 00:00:00     0.0555     0.0075     7.4290     0.0000      0.0408      0.0701
 time_2020-03-31 00:00:00    -0.2360     0.0079    -29.801     0.0000     -0.2516     -0.2205
 time_2020-06-30 00:00:00     0.2207     0.0089     24.697     0.0000      0.2032      0.2382
 time_2020-09-30 00:00:00     0.0507     0.0077     6.5745     0.0000      0.0356      0.0659
 time_2020-12-31 00:00:00     0.1076     0.0098     10.997     0.0000      0.0884      0.1268
 time_2021-03-31 00:00:00     0.0396     0.0073     5.4146     0.0000      0.0253      0.0540
 time_2021-06-30 00:00:00     0.0132     0.0065     2.0181     0.0436      0.0004      0.0260
 time_2021-09-30 00:00:00    -0.0374     0.0069    -5.4056     0.0000     -0.0509     -0.0238
 time_2021-12-31 00:00:00     0.0637     0.0067     9.4875     0.0000      0.0505      0.0768
 time_2022-03-31 00:00:00    -0.0409     0.0077    -5.3127     0.0000     -0.0560     -0.0258
 time_2022-06-30 00:00:00    -0.0965     0.0069    -13.904     0.0000     -0.1102     -0.0829
 time_2022-09-30 00:00:00    -0.0199     0.0070    -2.8179     0.0048     -0.0337     -0.0060
 time_2022-12-31 00:00:00     0.1425     0.0080     17.770     0.0000      0.1268      0.1582
 time_2023-03-31 00:00:00     0.0683     0.0078     8.7383     0.0000      0.0530      0.0836
 time_2023-06-30 00:00:00    -0.0024     0.0064    -0.3813     0.7029     -0.0150      0.0101
 time_2023-09-30 00:00:00    -0.0026     0.0072    -0.3675     0.7132     -0.0167      0.0114
 time_2023-12-31 00:00:00     0.1042     0.0078     13.397     0.0000      0.0889      0.1194
 time_2024-03-31 00:00:00     0.0348     0.0075     4.6520     0.0000      0.0201      0.0495
 time_2024-06-30 00:00:00    -0.0352     0.0067    -5.2554     0.0000     -0.0483     -0.0221
 time_2024-09-30 00:00:00     0.0486     0.0074     6.5920     0.0000      0.0342      0.0631
 time_2024-12-31 00:00:00    -0.0202     0.0070    -2.8939     0.0038     -0.0339     -0.0065
 time_2025-03-31 00:00:00     0.0332     0.0081     4.1079     0.0000      0.0173      0.0490
 time_2025-06-30 00:00:00     0.0403     0.0077     5.2450     0.0000      0.0253      0.0554
 time_2025-09-30 00:00:00     0.0188     0.0067     2.8145     0.0049      0.0057      0.0319
 ============================================================================================
 RandomEffectsResults, id: 0x7fb4d01c9450}